"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

type Language = "vi" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  vi: {
    "nav.home": "Trang chủ",
    "nav.my_courses": "Khóa học của tôi",
    "nav.live": "Lịch học Live",
    "nav.explore": "Khám phá",
    "nav.settings": "Cài đặt",
    "nav.admin": "Quản lý hệ thống",
    "nav.logout": "Đăng xuất",
    "auth.title": "Xóa bỏ khoảng cách, Đột phá kỹ năng",
    "auth.check1": "Lộ trình học cá nhân hóa bằng AI",
    "auth.check2": "Video bảo mật — không lo mất chất xám",
    "auth.check3": "Cộng đồng học viên tương tác thật",
    "auth.joined": "Đã có 100+ học viên tham gia",
    "auth.login_title": "Chào mừng trở lại",
    "auth.login_subtitle": "Đăng nhập để tiếp tục hành trình học tập",
    "auth.register_title": "Bắt đầu hành trình",
    "auth.register_subtitle": "Tạo tài khoản để mở khóa tiềm năng của bạn",
    "auth.email": "Địa chỉ Email",
    "auth.password": "Mật khẩu",
    "auth.login_btn": "Đăng nhập",
    "auth.register_btn": "Đăng ký",
    "auth.no_account": "Chưa có tài khoản?",
    "auth.have_account": "Đã có tài khoản?",
    "auth.google_login": "Tiếp tục với Google",
    "dashboard.welcome": "Chào buổi sáng",
    "dashboard.stats_users": "Tổng người dùng",
    "dashboard.stats_courses": "Khóa học hoạt động",
    "dashboard.stats_lessons": "Bài học đã xem",
    "dashboard.recommended": "Được AI gợi ý cho bạn",
    "dashboard.continue": "Tiếp tục học",
    "dashboard.start": "Bắt đầu ngay",
    "dashboard.all_courses": "Tất cả khóa học",
    "dashboard.my_learning": "Lộ trình của tôi",
    "dashboard.no_courses": "Bạn chưa tham gia khóa học nào",
    "dashboard.view_all": "Xem tất cả",
    "dashboard.lessons_remaining": "bài học còn lại",
    "dashboard.stats_minutes": "Phút học tập",
    "dashboard.stats_streak": "Ngày liên tiếp",
    "field.management": "Quản trị",
    "field.softskills": "Kỹ năng mềm",
    "field.it": "Lập trình",
    "field.marketing": "Marketing",
    "common.minutes": "phút",
    "common.lessons": "bài",
    "course.management_title": "Nhập Môn Quản Trị Doanh Nghiệp Hiện Đại",
    "course.management_desc": "Khóa học dành cho người mới bắt đầu tìm hiểu về quản trị doanh nghiệp, kỹ năng ra quyết định và quản lý đội nhóm.",
    "course.softskills_title": "Kỹ Năng Giao Tiếp & Thuyết Trình Chuyên Nghiệp",
    "course.softskills_desc": "Cải thiện khả năng giao tiếp, lắng nghe chủ động và xây dựng bài thuyết trình thuyết phục.",
    "course.it_title": "Python Cơ Bản — Từ Số Không Đến Có Thể Code",
    "course.it_desc": "Làm quen với tư duy lập trình và ngôn ngữ Python thông qua các ví dụ thực tế.",
    "course.marketing_title": "Digital Marketing Từ A-Z Cho Người Mới",
    "admin.management": "Quản trị hệ thống",
    "admin.description": "Theo dõi và quản lý toàn bộ hoạt động của nền tảng",
    "admin.overview": "Tổng quan",
    "admin.users": "Người dùng",
    "admin.courses": "Khóa học",
    "admin.live_sessions_tab": "Live Session",
    "explore.title": "Khám phá khóa học",
    "explore.desc": "Tìm kiếm khóa học phù hợp với mục tiêu của bạn",
    "explore.all": "Tất cả",
    "mycourses.title": "Khóa học của tôi",
    "mycourses.desc": "Theo dõi tiến độ học tập của bạn",
    "mycourses.learning": "Đang học",
    "mycourses.completed": "Đã hoàn thành",
    "mycourses.empty": "Bạn chưa bắt đầu khóa học nào",
    "mycourses.empty_desc": "Hãy khám phá các khóa học thú vị và bắt đầu hành trình nâng cao kỹ năng của bạn nhé.",
    "live.title": "Lịch học Live Session",
    "live.desc": "Tham gia các buổi học trực tuyến cùng giảng viên để giải đáp thắc mắc và đào sâu kiến thức.",
    "live.not_started": "Chưa bắt đầu",
    "live.room": "Phòng học trực tuyến",
    "common.home": "Trang chủ",
    "common.system_management": "Quản lý hệ thống",
    "admin.active_courses": "Khóa học đang mở",
    "admin.active_today": "Đang học hôm nay",
    "admin.live_sessions": "Live đang diễn ra",
    "admin.new_users_chart": "Người dùng mới (7 ngày qua)",
    "admin.popular_fields": "Lĩnh vực phổ biến nhất",
    "admin.user_groups": "Nhóm người dùng",
    "admin.user_groups_desc": "Phân loại học viên theo vai trò nghề nghiệp",
    "admin.pain_points": "Vấn đề gặp phải",
    "admin.pain_points_desc": "Top 5 rào cản lớn nhất của học viên",
    "admin.loading_error": "Lỗi tải thống kê",
    "admin.upcoming": "Sắp tới",
    "admin.today": "hôm nay",
    "admin.courses.status_published": "Đang mở",
    "admin.courses.status_hidden": "Ẩn",
    "admin.courses.manage_lessons": "Quản lý bài học",
    "admin.courses.edit_zalo": "Sửa Zalo",
    "admin.courses.add_zalo": "Thêm Zalo",
    "admin.courses.no_zalo": "Chưa có link Zalo",
    "admin.courses.lesson_list": "Danh sách Video bài học",
    "admin.courses.edit_video": "Sửa Video",
    "admin.courses.edit_title": "Sửa Tiêu đề",
    "admin.courses.edit_summary": "Sửa Tóm tắt",
    "admin.courses.editing": "Đang sửa...",
    "admin.courses.save_summary": "Lưu tóm tắt",
    "admin.courses.save_title": "Lưu tiêu đề",
    "admin.courses.cancel": "Hủy",
    "admin.courses.zalo_title": "Cập nhật link nhóm Zalo",
    "admin.courses.save_link": "Lưu link",
    "admin.courses.summary_label": "Tóm tắt / Nội dung chính",
    "admin.courses.tip": "Mẹo: Sử dụng xuống dòng để ngăn cách các ý chính.",
    "usertype.STUDENT": "Sinh viên",
    "usertype.PROFESSIONAL": "Người đi làm",
    "usertype.CAREER_CHANGER": "Chuyển ngành",
    "usertype.INSTRUCTOR": "Giảng viên",
    "usertype.UNKNOWN": "Chưa xác định",
    "painpoint.TIME": "Thiếu thời gian",
    "painpoint.GUIDANCE": "Thiếu lộ trình",
    "painpoint.COST": "Chi phí cao",
    "painpoint.INTERACTION": "Thiếu tương tác",
    "painpoint.PRACTICE": "Ít thực hành",
    "day.Mon": "T2",
    "day.Tue": "T3",
    "day.Wed": "T4",
    "day.Thu": "T5",
    "day.Fri": "T6",
    "day.Sat": "T7",
    "day.Sun": "CN",
    "dashboard.recommended": "Được AI gợi ý cho bạn",
    "dashboard.continue": "Tiếp tục học",
    "admin.users.search_placeholder": "Tìm theo tên hoặc email...",
    "admin.users.export": "Xuất CSV",
    "admin.users.header_user": "NGƯỜI DÙNG",
    "admin.users.header_type": "LOẠI",
    "admin.users.header_field": "LĨNH VỰC",
    "admin.users.header_pain": "VẤN ĐỀ ĐANG GẶP",
    "admin.users.header_course": "KHÓA HỌC",
    "admin.users.header_progress": "TIẾN ĐỘ",
    "admin.users.header_joined": "THAM GIA",
    "admin.users.not_started": "Chưa bắt đầu",
    "painpoint.Thiếu kỹ năng thực tế để xin việc": "Thiếu kỹ năng thực tế để xin việc",
    "painpoint.Không biết bắt đầu từ đâu": "Không biết bắt đầu từ đâu",
    "painpoint.Chi phí các khóa học quá cao": "Chi phí các khóa học quá cao",
    "painpoint.Thiếu sự tương tác với giảng viên": "Thiếu sự tương tác với giảng viên",
    "painpoint.Khó khăn trong việc sắp xếp thời gian": "Khó khăn trong việc sắp xếp thời gian",
    "settings.title": "Cài đặt hệ thống",
    "settings.language": "Ngôn ngữ hiển thị",
    "settings.profile": "Thông tin cá nhân",
    "settings.save": "Lưu thay đổi",
    "common.loading": "Đang tải...",
  },
  en: {
    "nav.home": "Home",
    "nav.my_courses": "My Courses",
    "nav.live": "Live Sessions",
    "nav.explore": "Explore",
    "nav.settings": "Settings",
    "nav.admin": "Admin Dashboard",
    "nav.logout": "Logout",
    "auth.title": "Closing the Gap, Breaking Skill Barriers",
    "auth.check1": "AI-Personalized Learning Paths",
    "auth.check2": "Secure Videos — Protect Your Knowledge",
    "auth.check3": "Real Interactive Student Community",
    "auth.joined": "100+ Students already joined",
    "auth.login_title": "Welcome Back",
    "auth.login_subtitle": "Login to continue your learning journey",
    "auth.register_title": "Start Your Journey",
    "auth.register_subtitle": "Create an account to unlock your potential",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.login_btn": "Login",
    "auth.register_btn": "Register",
    "auth.no_account": "Don't have an account?",
    "auth.have_account": "Already have an account?",
    "auth.google_login": "Continue with Google",
    "dashboard.welcome": "Good morning",
    "dashboard.stats_users": "Total Users",
    "dashboard.stats_courses": "Active Courses",
    "dashboard.stats_lessons": "Lessons Viewed",
    "dashboard.recommended": "AI Recommended for you",
    "dashboard.continue": "Continue Learning",
    "dashboard.start": "Start Now",
    "dashboard.all_courses": "All Courses",
    "dashboard.my_learning": "My Learning Path",
    "dashboard.no_courses": "You haven't joined any courses yet",
    "dashboard.view_all": "View All",
    "dashboard.lessons_remaining": "lessons remaining",
    "dashboard.stats_minutes": "Learning Minutes",
    "dashboard.stats_streak": "Day Streak",
    "field.management": "Management",
    "field.softskills": "Soft Skills",
    "field.it": "Programming",
    "field.marketing": "Marketing",
    "common.minutes": "mins",
    "common.lessons": "lessons",
    "course.management_title": "Introduction to Modern Enterprise Management",
    "course.management_desc": "A course for beginners to learn about business management, decision-making skills, and team management.",
    "course.softskills_title": "Professional Communication & Presentation Skills",
    "course.softskills_desc": "Improve communication, active listening, and building persuasive presentations.",
    "course.it_title": "Basic Python — From Zero to Code",
    "course.it_desc": "Get familiar with programming logic and Python language through practical examples.",
    "course.marketing_title": "Digital Marketing A-Z for Beginners",
    "course.marketing_desc": "Grasp basic concepts of digital marketing, content marketing, and performance measurement.",
    "admin.management": "System Management",
    "admin.description": "Monitor and manage all platform activities",
    "admin.overview": "Overview",
    "admin.users": "Users",
    "admin.courses": "Courses",
    "admin.live_sessions_tab": "Live Session",
    "explore.title": "Explore Courses",
    "explore.desc": "Find the course that fits your goals",
    "explore.all": "All",
    "mycourses.title": "My Courses",
    "mycourses.desc": "Track your learning progress",
    "mycourses.learning": "Learning",
    "mycourses.completed": "Completed",
    "mycourses.empty": "You haven't started any courses yet",
    "mycourses.empty_desc": "Explore exciting courses and start your journey to level up your skills.",
    "live.title": "Live Session Schedule",
    "live.desc": "Join online sessions with instructors to get answers and deepen your knowledge.",
    "live.not_started": "Not Started",
    "live.room": "Online Classroom",
    "common.home": "Home",
    "common.system_management": "System Management",
    "admin.active_courses": "Active Courses",
    "admin.active_today": "Active Today",
    "admin.live_sessions": "Live Sessions",
    "admin.new_users_chart": "New Users (Last 7 Days)",
    "admin.popular_fields": "Most Popular Fields",
    "admin.user_groups": "User Groups",
    "admin.user_groups_desc": "Classifying students by professional role",
    "admin.pain_points": "Pain Points",
    "admin.pain_points_desc": "Top 5 biggest barriers for students",
    "admin.loading_error": "Error loading statistics",
    "admin.upcoming": "Upcoming",
    "admin.today": "today",
    "admin.courses.status_published": "Active",
    "admin.courses.status_hidden": "Hidden",
    "admin.courses.manage_lessons": "Manage Lessons",
    "admin.courses.edit_zalo": "Edit Zalo",
    "admin.courses.add_zalo": "Add Zalo",
    "admin.courses.no_zalo": "No Zalo link",
    "admin.courses.lesson_list": "Lesson Video List",
    "admin.courses.edit_video": "Edit Video",
    "admin.courses.edit_title": "Edit Title",
    "admin.courses.edit_summary": "Edit Summary",
    "admin.courses.editing": "Editing...",
    "admin.courses.save_summary": "Save Summary",
    "admin.courses.save_title": "Save Title",
    "admin.courses.cancel": "Cancel",
    "admin.courses.zalo_title": "Update Zalo Group Link",
    "admin.courses.save_link": "Save Link",
    "admin.courses.summary_label": "Summary / Key Content",
    "admin.courses.tip": "Tip: Use line breaks to separate key points.",
    "usertype.STUDENT": "Student",
    "usertype.PROFESSIONAL": "Professional",
    "usertype.CAREER_CHANGER": "Career Changer",
    "usertype.INSTRUCTOR": "Instructor",
    "usertype.UNKNOWN": "Unknown",
    "painpoint.TIME": "Lack of time",
    "painpoint.GUIDANCE": "No roadmap",
    "painpoint.COST": "High cost",
    "painpoint.INTERACTION": "No interaction",
    "painpoint.PRACTICE": "Few practice",
    "day.Mon": "Mon",
    "day.Tue": "Tue",
    "day.Wed": "Wed",
    "day.Thu": "Thu",
    "day.Fri": "Fri",
    "day.Sat": "Sat",
    "day.Sun": "Sun",
    "dashboard.recommended": "AI Recommended for you",
    "dashboard.continue": "Continue Learning",
    "dashboard.start": "Start Learning Now",
    "admin.users.search_placeholder": "Search by name or email...",
    "admin.users.export": "Export CSV",
    "admin.users.header_user": "USER",
    "admin.users.header_type": "TYPE",
    "admin.users.header_field": "FIELD",
    "admin.users.header_pain": "PAIN POINT",
    "admin.users.header_course": "COURSE",
    "admin.users.header_progress": "PROGRESS",
    "admin.users.header_joined": "JOINED",
    "admin.users.not_started": "Not started",
    "course.back": "Back to Dashboard",
    "course.lesson": "Lesson",
    "course.progress": "Progress",
    "course.learning_status": "Learning",
    "course.summary": "Lesson Summary",
    "course.mark_complete": "Mark as Completed",
    "course.completed": "Lesson Completed",
    "course.zalo_group": "Zalo Community Group",
    "course.lock_msg": "Complete previous lesson to unlock",
    "course.live_now": "Live Now",
    "course.live_msg": "Join the live room to ask questions!",
    "ai.title": "VieSync Learning Assistant",
    "ai.status": "READY TO HELP",
    "ai.welcome": "Welcome to the course! I am the VieSync Learning Assistant. Here are some topics I can help you with:",
    "ai.suggest_1": "How to overcome fear of public speaking?",
    "ai.suggest_2": "How to listen more actively?",
    "ai.suggest_3": "Handling difficult questions?",
    "ai.suggest_4": "How to chat with other students?",
    "ai.input_placeholder": "Do you have any other questions?",
    "course.Kỹ Năng Giao Tiếp & Thuyết Trình Chuyên Nghiệp_title": "Professional Communication & Presentation Skills",
    "lesson.Nghệ Thuật Lắng Nghe Chủ Động_title": "The Art of Active Listening",
    "lesson.Lắng nghe chủ động là gì?": "What is active listening?",
    "lesson.Các rào cản khi lắng nghe.": "Barriers to listening.",
    "lesson.Kỹ thuật phản hồi.": "Feedback techniques.",
    "painpoint.Thiếu kỹ năng thực tế để xin việc": "Lack of practical skills for job seeking",
    "painpoint.Không biết bắt đầu từ đâu": "Don't know where to start",
    "painpoint.Chi phí các khóa học quá cao": "Course fees are too high",
    "painpoint.Thiếu sự tương tác với giảng viên": "Lack of interaction with instructors",
    "painpoint.Khó khăn trong việc sắp xếp thời gian": "Difficulty in time management",
    "settings.title": "System Settings",
    "settings.language": "Display Language",
    "settings.profile": "Personal Profile",
    "settings.save": "Save Changes",
    "common.loading": "Loading...",
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("vi")

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Language
    if (saved) setLanguage(saved)
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("lang", lang)
  }

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error("useLanguage must be used within LanguageProvider")
  return context
}
